import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Poppins } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/header";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import SiteFooter from "@/components/site-footer";
import { SidebarProvider } from "@/components/ui/sidebar";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const latoSans = Lato({
  variable: "--font-lato-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${latoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider
          defaultOpen={false}
          style={
            {
              // "--sidebar-width": "14rem",
              // "--sidebar-width-mobile": "10rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar />
          <div className="@container/wrapper flex min-h-screen w-full flex-col">
            <SiteHeader />
            <main className="@container/main mb-8 mx-auto w-full">
              {props.children}
            </main>
            <SiteFooter />
          </div>
        </SidebarProvider>{" "}
      </body>
    </html>
  );
}
